{
  "name": "ebfapp",
  "version": "1.0.0",
  "description": "Your Node.js project",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "express": "^4.18.2"  // 示例：添加 Express 依赖
  }
}
