name: Node.js CI

on:
  push:
    branches: [main]  # 当推送到 main 分支时触发
  pull_request:
    branches: [main]  # 当 PR 请求发往 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为运行环境

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # 支持 Node.js 14 和 16

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install  # 安装依赖

    - run: npm test  # 运行测试（如果你有）

    - run: npm run build  # 如果有构建步骤，则运行构建
